# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-30 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=100, verbose_name='Salt命令')),
                ('doc', models.TextField(blank=True, max_length=1000, verbose_name='帮助文档')),
            ],
            options={
                'verbose_name': 'Salt命令',
                'verbose_name_plural': 'Salt命令列表',
            },
        ),
        migrations.CreateModel(
            name='Minions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minion', models.CharField(max_length=50, unique=True, verbose_name='客户端')),
                ('grains', models.TextField(blank=True, max_length=500, verbose_name='Grains信息')),
                ('pillar', models.TextField(blank=True, max_length=500, verbose_name='Pillar信息')),
                ('status', models.CharField(choices=[('Unknown', 'Unknown'), ('Accepted', 'Accepted'), ('Denied', 'Denied'), ('Unaccepted', 'Unaccepted'), ('Rejected', 'Rejected')], default='Unknown', max_length=20, verbose_name='在线状态')),
            ],
            options={
                'verbose_name': 'Salt客户端',
                'verbose_name_plural': 'Salt客户端列表',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(default='execution', max_length=20, verbose_name='Salt模块类型')),
                ('name', models.CharField(max_length=20, verbose_name='Salt模块名称')),
            ],
            options={
                'verbose_name': 'Salt模块',
                'verbose_name_plural': 'Salt模块列表',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=20, verbose_name='执行方式')),
                ('fun', models.CharField(max_length=50, verbose_name='命令')),
                ('arg', models.CharField(blank=True, max_length=255, verbose_name='参数')),
                ('tgt_type', models.CharField(max_length=20, verbose_name='目标类型')),
                ('jid', models.CharField(blank=True, max_length=50, verbose_name='任务号')),
                ('minions', models.CharField(blank=True, max_length=500, verbose_name='目标主机')),
                ('result', models.TextField(blank=True, verbose_name='返回结果')),
                ('user', models.CharField(max_length=50, verbose_name='操作用户')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': '命令返回结果',
                'verbose_name_plural': '命令返回结果',
            },
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set([('client', 'name')]),
        ),
        migrations.AddField(
            model_name='command',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Module', verbose_name='所属模块'),
        ),
        migrations.AlterUniqueTogether(
            name='command',
            unique_together=set([('module', 'cmd')]),
        ),
    ]
