# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-30 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, unique=True, verbose_name='IP地址')),
                ('hostname', models.CharField(blank=True, max_length=30, verbose_name='主机名')),
                ('fqdn', models.CharField(blank=True, max_length=50, verbose_name='计算机全称')),
                ('domain', models.CharField(blank=True, max_length=50, verbose_name='域名')),
                ('macaddress', models.CharField(blank=True, max_length=40, verbose_name='MAC地址')),
                ('os', models.CharField(blank=True, max_length=50, verbose_name='操作系统')),
                ('osarch', models.CharField(blank=True, max_length=50, verbose_name='系统架构')),
                ('osrelease', models.CharField(blank=True, max_length=50, verbose_name='系统版本')),
                ('manufacturer', models.CharField(blank=True, max_length=20, verbose_name='厂商')),
                ('productname', models.CharField(blank=True, max_length=30, verbose_name='产品型号')),
                ('serialnumber', models.CharField(blank=True, max_length=80, verbose_name='序列号')),
                ('cpu_model', models.CharField(blank=True, max_length=50, verbose_name='CPU型号')),
                ('cpu_nums', models.PositiveSmallIntegerField(blank=True, verbose_name='CPU线程数')),
                ('cpu_groups', models.PositiveSmallIntegerField(blank=True, verbose_name='CPU物理核数')),
                ('mem', models.CharField(blank=True, max_length=5, verbose_name='内存大小')),
                ('virtual', models.CharField(blank=True, max_length=20, verbose_name='虚拟环境')),
            ],
            options={
                'verbose_name': '主机资产信息',
                'verbose_name_plural': '主机资产信息管理',
            },
        ),
        migrations.CreateModel(
            name='HostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='使用状态')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机列表',
            },
        ),
        migrations.CreateModel(
            name='IdcAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc_name', models.CharField(max_length=20, unique=True, verbose_name='机房名称')),
                ('idc_operators', models.CharField(choices=[('DX', '电信'), ('LT', '联通'), ('YD', '移动'), ('ZJ', '自建')], default='DX', max_length=20, verbose_name='运营商')),
                ('idc_location', models.CharField(blank=True, max_length=30, verbose_name='机房地址')),
                ('idc_contacts', models.CharField(blank=True, max_length=30, verbose_name='联系电话')),
                ('remark', models.TextField(blank=True, default='', max_length=50, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'IDC资产信息',
                'verbose_name_plural': 'IDC资产信息管理',
            },
        ),
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, verbose_name='维护人员')),
            ],
            options={
                'verbose_name': '维护人员',
                'verbose_name_plural': '维护人员列表',
            },
        ),
        migrations.AddField(
            model_name='hostlist',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.IdcAsset', verbose_name='所属机房'),
        ),
        migrations.AddField(
            model_name='hostlist',
            name='ip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostlist.HostAsset', verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='hostlist',
            name='maintainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostlist.Maintainer', verbose_name='维护人员'),
        ),
    ]
