# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-31 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostasset',
            name='ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP地址'),
        ),
    ]
